// Mock data for building and demoing without a backend. Same shapes as the API (fixtures/ in the repo root).
// Everything shown from here is labelled "Mock data" in the UI.
import snapshotJson from './snapshot.json';
import recommendationJson from './recommendation.json';
import explainJson from './explain.json';
import type { CurrentView, DecisionRecord, ExplainResponse, HealthReport, NetworkSnapshot, Recommendation } from '../api/types';

export const mockSnapshot = snapshotJson as unknown as NetworkSnapshot;

const rec = { ...(recommendationJson as unknown as Recommendation), tick: mockSnapshot.tick, id: 'rec-example' };

export const mockCurrent: CurrentView = {
  tick: mockSnapshot.tick,
  source: 'mock',
  error: null,
  recommendation: rec,
  gate: {
    requires_human: true, executable: true, auto_execute: false, mode: 'SUPERVISED', confidence: 0.74,
    reasons: ['confidence 0.74 < 0.80', 'active event: demand_spike, route_disruption'], blocked_legs: [],
  },
  record_stage: 'gated',
  autonomy: {
    mode: 'SUPERVISED', armed: false, healthy_ticks: 0, confidence: 0.74, target_mode: 'SUPERVISED',
    factors: [
      { key: 'fit', label: 'Forecast fit', weight: 0.25, value: 0.77 },
      { key: 'twin', label: 'Twin accuracy', weight: 0.2, value: 0.85 },
      { key: 'fresh', label: 'Data freshness', weight: 0.2, value: 1 },
      { key: 'normal', label: 'Demand normality', weight: 0.15, value: 0.7 },
      { key: 'health', label: 'Component health', weight: 0.1, value: 1 },
      { key: 'crisis', label: 'No active crisis', weight: 0.1, value: 0.6 },
    ],
    thresholds: { autonomous_min: 0.8, manual_below: 0.6, healthy_ticks_to_climb: 3 },
    log: [
      { tick: 97, message: 'Mode AUTONOMOUS -> SUPERVISED (confidence 0.74).' },
      { tick: 90, message: 'Operator re-armed Autonomous.' },
    ],
  },
};

export const mockHealth: HealthReport = {
  status: 'degraded', tick: mockSnapshot.tick, snapshot_age_seconds: 0.4,
  components: [
    { name: 'Backend API', status: 'healthy', detail: null },
    { name: 'Simulator', status: 'healthy', detail: null },
    { name: 'Operational state', status: 'healthy', detail: null },
    { name: 'Event stream', status: 'degraded', detail: 'SSE down, polling REST' },
    { name: 'Decision engine', status: 'healthy', detail: null },
    { name: 'Explanation', status: 'healthy', detail: 'template explanations (LLM off)' },
  ],
};

export const mockDecisions: DecisionRecord[] = [
  {
    decision_id: 'rec-example', sim_tick: mockSnapshot.tick, created_at: new Date().toISOString(), stage: 'gated',
    versions: rec.versions, mode: 'SUPERVISED', recommendation: rec, gate: mockCurrent.gate, approval: null,
    submissions: [], outcome: null, twin_check: null, observed: { active_events: ['demand_spike', 'route_disruption'] },
    prediction: { model_confidence: 0.74, decision_confidence: 0.74 },
    candidates: (rec.futures ?? []).map((f) => ({ id: f.candidate_id, label: f.label, unmet_l: f.network_unmet_liters })),
  },
  {
    decision_id: 'rec-example-earlier', sim_tick: mockSnapshot.tick - 6, created_at: new Date(Date.now() - 72e3).toISOString(),
    stage: 'submitted', versions: rec.versions, mode: 'SUPERVISED', recommendation: { ...rec, id: 'rec-example-earlier', tick: mockSnapshot.tick - 6 },
    gate: { ...mockCurrent.gate!, reasons: ['confidence 0.78 < 0.80'], confidence: 0.78 },
    approval: { decision: 'approved', by: 'operator', reason: 'Matches the spike playbook', modified: false },
    submissions: [], outcome: null, twin_check: { predicted_l: 200, actual_l: 240, error_l: 40 }, observed: null,
    prediction: null, candidates: [],
  },
];

/** Generated by the backend's template copilot from the same fixtures. */
export const mockExplain = explainJson as ExplainResponse;
